
create schema if not exists booking;
use booking;


DROP TABLE IF EXISTS hotel;
CREATE TABLE IF NOT EXISTS hotel
(
 id bigint generated by default as identity not null primary key,
 name varchar(255) null,
 city varchar(255) null,
 hotel_rating smallint null,
 constraint hotel_id_uindex
 unique (id)
);


DROP TABLE IF EXISTS room;
create table IF NOT EXISTS room
(
 id bigint generated by default as identity not null primary key,
 number int null,
 category enum('STANDART', 'SUITE', 'BUSINESS',  'APARTMENT', 'PRESIDENT') null,
 price decimal not null,
 meals_type enum('NONE', 'BREAKFAST', 'BREAKFAST_DINNER',  'SELF_CATERING') null,
 meal_price decimal null,
 cleaning_price decimal null,
 hotel_id bigint not null,
 constraint room_id_uindex
 unique (id)
);


DROP TABLE IF EXISTS user;
create table IF NOT EXISTS user
(
 id bigint generated by default as identity not null primary key,
 name varchar(255) null,
 email varchar(255) null UNIQUE,
 role enum('ANONIM', 'USER') null,
 constraint user_id_uindex
 unique (id)
);


DROP TABLE IF EXISTS user_account;
create table IF NOT EXISTS user_account
(
 id bigint generated by default as identity not null primary key,
 user_id bigint not null,
 constraint userAccount_id_uindex
 unique (id)
);


DROP TABLE IF EXISTS booking;
create table IF NOT EXISTS booking
(
 id bigint generated by default as identity not null primary key,
 user_account_id bigint not null,
 room_id bigint not null,
 arrival date not null default CURRENT_DATE,
 departure date not null default CURRENT_DATE,
 total_price decimal null,
 constraint booking_id_uindex
 unique (id)
);

